---
- name: User & Group Management Demo
  hosts: all
  become: yes
  tasks:

    - name: Ensure application group exists
      group:
        name: "{{ app_group }}"
        state: present

    - name: Ensure application user exists
      user:
        name: "{{ app_user }}"
        group: "{{ app_group }}"
        password: "{{ app_password }}"
        create_home: yes
        shell: /bin/bash
        state: present

    - name: Create work directory for application user
      file:
        path: "{{ workdir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0750'

    - name: Create information file owned by application user
      copy:
        dest: "{{ workdir }}/info.txt"
        content: "user {{ app_user }} sudah berhasil dibuat"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
