---
- name: User & Group Management Demo
  hosts: all
  become: yes

  vars:
    app_group: inventorygrp
    app_password: "{{ 'P@ssw0rd' | password_hash('sha512') }}"
    workdir: /opt/inventory

  tasks:

    - name: Ensure application group exists
      group:
        name: "{{ app_group }}"
        state: present

    - name: Ensure application user exists
      user:
        name: "{{ app_user }}"
        group: "{{ app_group }}"
        password: "{{ app_password }}"
        create_home: yes
        shell: /bin/bash
        state: present

    - name: Create work directory for application user
      file:
        path: "{{ workdir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0750'

    - name: Create information file owned by application user
      copy:
        dest: "{{ workdir }}/info.txt"
        content: "file ini dibuat menggunakan user {{ app_user }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
